src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    // /**
    //  * @ORM\Column(type="string", length=255, nullable=true)
    //  *
    //  * @var string|null
    //  */
    // private $fileName;

    // /**
    //  * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName")
    //  * @Assert\Image(mimeTypes={"image/jpeg","image/png"})
    //  * @var File|null
    //  */
    // private $imageFile;

    // /**
    //  * @ORM\Column(type="datetime", nullable=true)
    //  */
    // private $updated_at;
    

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 5, max = 255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{2}\s?[0-9]{3}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     *  @Assert\All({
     *   @Assert\Image(
     *     maxSize="1000k",
     *     maxSizeMessage="Le fichier excède 1000Ko.",
     *     mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/gif"},
     *     mimeTypesMessage= "formats autorisés: png, jpeg, jpg, gif"
     *   )
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PropertyLike", mappedBy="property")
     */
    private $likes;

    public function __construct()
    {
        $this->options = new ArrayCollection();
        $this->created_at = new \Datetime();
        $this->pictures = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug() : string
    {
        return (new Slugify())->slugify($this->title); 
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice() : string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    // /**
    //  * Get the value of imageFile
    //  *
    //  * @return  File|null
    //  */ 
    // public function getImageFile()
    // {
    //     return $this->imageFile;
    // }

    // /**
    //  * Set the value of imageFile
    //  *
    //  * @param  File|null  $imageFile
    //  *
    //  * @return  self
    //  */ 
    // public function setImageFile($imageFile)
    // {
    //     $this->imageFile = $imageFile;

    //     if ($this->imageFile instanceof UploadedFile) {
    //         $this->updated_at = new \DateTime('now');
    //     }

    //     return $this;
    // }

    // /**
    //  * Get the value of fileName
    //  *
    //  * @return  string|null
    //  */ 
    // public function getFileName()
    // {
    //     return $this->fileName;
    // }

    // /**
    //  * Set the value of fileName
    //  *
    //  * @param  string|null  $fileName
    //  *
    //  * @return  self
    //  */ 
    // public function setFileName($fileName)
    // {
    //     $this->fileName = $fileName;

    //     return $this;
    // }

    // public function getUpdatedAt(): ?\DateTimeInterface
    // {
    //     return $this->updated_at;
    // }

    // public function setUpdatedAt(\DateTimeInterface $updated_at): self
    // {
    //     $this->updated_at = $updated_at;

    //     return $this;
    // }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
            return $this->pictures->first();
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get maxSize="1000k",
     */ 
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * Set maxSize="1000k",
     *
     * @return  self
     */ 
    public function setPictureFiles($pictureFiles)
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices(),
                // 'expanded' => true,
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true,
                // 'expanded' => true,
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true,
            ])
            ->add('city')
            ->add('adress')
            ->add('complement')
            ->add('postal_code')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('sold')
            ->add('created_at', DateType::class, [
                'format' => 'dd/MM/yyyy',
                'widget' => 'single_text',
                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,
                // adds a class that can be selected in JavaScript
                'attr' => ['class' => 'js-datepicker'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\Contact;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use Twig\Environment;
use App\Notification\ContactNotification;
use App\Form\ContactType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
//si on utilise l autowiring/
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
//si on avait utilisé le container mais c est pas comme ça qu on declare il faut aller dans services
// use Knp\Component\Pager\Paginator;
use ReCaptcha\ReCaptcha;
use Symfony\Component\Translation\TranslatorInterface;



class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/{_locale}/biens", name="property.index")
     * requirements:
     *     _locale: fr|en
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        // $repository = $this->getDoctrine()->getRepository(Property::class);
        // dump($repository);
        
        // $property = $this->repository->findAllVisible();
        // dump($property);

        //systeme de filtre
        //créé une entité qui va représenter notre recherche
        //créé un formulaire
        //gérer l'affichage du formulaire
        //gérer le traitement dans notre controller

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        // $paginator  = $this->get('knp_paginator');
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search), /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            6/*limit per page*/
        );
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties'   => $properties,
            'form'         => $form->createView()
        ]);
    }

    /**
     * @Route("/{_locale}/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*", })
     * requirements:
     *     _locale: fr|en
     */
    public function show(Property $property, string $slug, TranslatorInterface $translator, Request $request, \Swift_Mailer $mailer, Environment $renderer, ContactNotification $notification) : Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id'   => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        $contact = new Contact();
        $contact->setProperTy($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $notification->notify($contact);
            $message = (new \Swift_Message('Agence: ' .$contact->getProperty()->getTitle()))
            ->setFrom(['alexandre.houriez5@gmail.com'=> 'Mon Agence'])            
            ->setTo('alexandre.houriez@yahoo.fr')
            ->setReplyTo($contact->getEmail())
            ->setBody($renderer->render('emails/contact.html.twig', [
                'contact' => $contact
            ]), 'text/html');
            $mailer->send($message);

            $this->addFlash('success', $translator->trans('email.message.success'));
            return $this->redirectToRoute('property.show', [
                'id'   => $property->getId(),
                'slug' => $property->getSlug()
            ]);
            // ici ce sera pas une 301 on fait une redirection suite a un traitement corrct du formulaire
        }


        if(isset($_POST['g-recaptcha-response'])){
            $recaptcha = new ReCaptcha("6LdkbZ0UAAAAAHerBAiNFmD0MqdNLon2mq-1PBPd");
            $resp = $recaptcha->verify($_POST['g-recaptcha-response']);
            if ($resp->isSuccess()) {
                // Verified!
                // var_dump('Captcha valide');
            } else {
                $errors = $resp->getErrorCodes();
                // var_dump('Captcha invalide');
                // var_dump($errors);
            }
        }

        //$property = $this->repository->find($property);
        return $this->render('property/show.html.twig', [
            'property'     => $property,
            'current_menu' => 'properties',
            'form'         => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
    <div class="card mb-4">
    <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
    {% if property.picture %}
        <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}" class="card-img-top" style="width:100%;height:auto" alt="">
    {% else %}
        <img src="{{ "images/empty.jpg" | imagine_filter('thumb') }}" class="card-img-top" style="width:100%;height:auto" alt="">
    {% endif %}
    </a>
        <div class="card-body"><!--.card-body pour le padding -->
            <h5 class="card-title">
                <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
            </h5>
            <p class="card-text">{{ property.surface }}m<sup>2</sup> - {{ property.city }} ({{ property.postalCode }})</p>
            <div class="text-primary" style="font-weight:bold;font-size:2rem;">{{ property.getFormattedPrice }} €</div>
            <a href="{{ path('property_like', {'id': property.id}) }}" class="btn btn-link js-like float-right">
                {% if app.user and property.isLikedByUser(app.user) %}
                    <i class="fas fa-thumbs-up"></i>
                {% else %}
                    <i class="far fa-thumbs-up"></i>
                {% endif %}
                <span class="js-likes">{{ property.likes | length }}</span>
                <span class="js-label">{{ 'properties.like'|trans }}</span>
            </a>
        </div>
    </div>
</div>

templates/property/_property_likeByUser.html.twig
{% if app.user and property.isLikedByUser(app.user) %}
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="card mb-4">
        <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
        {% if property.picture %}
            <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}" class="card-img-top" style="width:100%;height:auto" alt="">
        {% else %}
            <img src="{{ "images/empty.jpg" | imagine_filter('thumb') }}" class="card-img-top" style="width:100%;height:auto" alt="">
        {% endif %}
        </a>
            <div class="card-body"><!--.card-body pour le padding -->
                <h5 class="card-title">
                    <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
                </h5>
                <p class="card-text">{{ property.surface }}m<sup>2</sup> - {{ property.city }} ({{ property.postalCode }})</p>
                <div class="text-primary" style="font-weight:bold;font-size:2rem;">{{ property.getFormattedPrice }} €</div>
                <a href="{{ path('property_like', {'id': property.id}) }}" class="btn btn-link js-like float-right">
                    {% if app.user and property.isLikedByUser(app.user) %}
                        <i class="fas fa-thumbs-up"></i>
                    {% else %}
                        <i class="far fa-thumbs-up"></i>
                    {% endif %}
                    <span class="js-likes">{{ property.likes | length }}</span>
                    <span class="js-label">J'aime</span>
                </a>
            </div>
        </div>
    </div>
{% endif %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain "messages" %}

{% block title %}
    {{ 'title.index'|trans }}
{% endblock title %}

{% block body %}
<div class="jumbotron">
        <div class="container">
        {{ form_start(form) }}
        <div class="row align-items-end">
                <div class="col-md-3"><div class="form-group">{{ form_row(form.minSurface, { 'attr': {'placeholder': 'form.search.minsurface'|trans } } ) }}</div></div>
                <div class="col-md-3"><div class="form-group">{{ form_row(form.maxPrice, { 'attr': {'placeholder': 'form.search.maxprice'|trans} } ) }}</div></div>
                <div class="col-md-3"><div class="form-group">{{ form_row(form.minPiece, { 'attr': {'placeholder': 'form.search.minpiece'|trans} } ) }}</div></div>
                <div class="col-md-2"><div class="form-group">{{ form_row(form.options) }}</div></div>
        </div>
        <div class="row align-items-end">
                <div class="col-md-8"><div class="form-group"><input type="text" value="" placeholder="{{ 'form.search.address'|trans }}" id="search_adress" class="form-control"></div></div>
                <div class="col-md-2"><div class="form-group">{{ form_row(form.distance, { 'attr': {'placeholder': "{{ 'form.search.distance'|trans }}"} }) }}</div></div>
                <div class="col-md-2"><div class="form-group"><button class="btn btn-primary"><span class="glyphicon glyphicon-search"></span>{{ 'form.search.search'|trans }}</button></div></div>
        </div>
        {{ form_end(form) }}
        </div>
</div>
<div class="container mt-4">
        <h1>{{ 'properties.index.title'|trans }}</h1>
        {# <div class="dropdown pull-left">
            <strong>Trier par:</strong>
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="true">
                <span>défault</span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li>{{ knp_pagination_sortable(properties, 'nom', 'name') }}</li>
                <li>{{ knp_pagination_sortable(properties, 'prix', 'price') }}</li>
            </ul>
        </div> #}
        <div class="row">
                {% for property in properties %}
                        {% include 'property/_property.html.twig' %}
                {% endfor %}
        </div>
        {# display navigation #}
        <div class="navigation">
        {{ knp_pagination_render(properties) }}
        </div>
</div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain "messages" %}

{% block title property.title %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        
        {% if not form.vars.valid %}
            <div class="alert alert-danger">
                Il y a eu une erreur lors de l'envoi de l'email
            </div>
        {% endif %}
        
        <div class="row">
            <div class="col-md-8">
                {# <div data-slider> #}
                <div>
                    {% if property.pictures is empty %}
                        <a class="single_image" href="{{ "images/empty.jpg" | imagine_filter('medium') }}">
                        <img src="{{ "images/empty.jpg" | imagine_filter('medium') }}" class="card-img-top" style="width:100%;height:auto" alt="">
                        </a>  
                    {% else %}
                    {# {% for picture in property.pictures %} #}
                        <a class="single_image" href="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('medium') }}">
                        <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('medium') }}" class="card-img-top main" style="width:100%;height:auto" alt="">
                        </a>
                    {# {% endfor %} #}
                    {% endif %}
                </div>
                {# </div> #}
                <div class="row">
                    {% if property.pictures | length > 1 %}
                        {% for picture in property.pictures %}
                            <div class="col-xs-3">
                                <a href="#"><img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('medium') }}" width="123" alt="" class="thumb" style="margin:13px 0px 0px 15px"></a>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="col-md-4">
                <h1>{{property.title}}</h1>
                <h2>{{property.rooms}} {{ 'show.jumbotron.rooms'|trans }} - {{property.surface}} m<sup>2</sup></h2>
                <h2>{{property.city}} ({{property.postalCode}})</h2>
                <div class="text-primary" style="font-size:3rem;font-weight:bold;">{{property.getFormattedPrice()}} €</div>       
                <a href="#" id="contactButton" class="btn btn-primary"{% if form.vars.submitted %} style="display:none" {% endif %}>{{ 'show.jumbotron.contact'|trans }}</a>
                <div id="contactForm" class="mt-4"{% if not form.vars.submitted %} style="display:none" {% endif %} >
                {{ form_start(form) }}
                <div class="row">
                    <div class="col">{{ form_row(form.firstname, {'label': 'show.contact.firstname'|trans}) }}</div>
                    <div class="col">{{ form_row(form.lastname, {'label': 'show.contact.lastname'|trans}) }}</div>
                </div>
                <div class="row">
                    <div class="col">{{ form_row(form.phone, {'label': 'show.contact.phone'|trans}) }}</div>
                    <div class="col">{{ form_row(form.email, {'label': 'show.contact.email'|trans}) }}</div>
                </div>
                <div class="row">
                    <div class="col">{{ form_row(form.message, {'label': 'show.contact.message'|trans}) }}</div>
                </div>
                <div class="g-recaptcha" data-sitekey="6LdkbZ0UAAAAAL48iOlThGAp9MUuzTiEZVqk8dKu"></div>
                <div class="">
                    <button class="btn btn-primary">{{ 'show.jumbotron.send'|trans }}</button>
                </div>
                {{ form_end(form) }}
                </div>       
            </div>
        </div>        
    </div>
</div>
<div class="container mt-4 mb-4">
    <p>
        {{property.description | raw | nl2br }}
    </p>

    <div class="row">
        <div class="col-md-8">
            <h2>{{ 'show.characteristics.characteristics'|trans }}</h2>
            <table class="table table-striped">
                <tr>
                    <td>{{ 'show.characteristics.surface'|trans }}</td>
                    <td>{{property.surface}} m<sup>2</sup></td>
                </tr>
                <tr>
                    <td>{{ 'show.characteristics.rooms'|trans }}</td>
                    <td>{{property.rooms}}</td>
                </tr>
                <tr>
                    <td>{{ 'show.characteristics.bedrooms'|trans }}</td>
                    <td>{{property.bedrooms}}</td>
                </tr>
                <tr>
                    <td>{{ 'show.characteristics.floor'|trans }}</td>
                    <td>{{property.floor}}</td>
                </tr>
                <tr>
                    <td>{{ 'show.characteristics.heating'|trans }}</td>
                    <td>{{property.heatType}}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>{{ 'show.specificities'|trans }}</h2>
            <ul class="list-group">
            {% for option in property.options %}
                <li class="list-group-item">{{ option.name }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div id="map" class="mt-3" style="width: 100%; height: 400px" data-lat="{{ property.lat }}" data-lng="{{ property.lng }}"></div>   
</div>
{% endblock %}

{% block javascripts %}
  <script src="https://www.google.com/recaptcha/api.js?render=6LdkbZ0UAAAAAL48iOlThGAp9MUuzTiEZVqk8dKu"></script>
  <script>
  grecaptcha.ready(function() {
      grecaptcha.execute('6LdkbZ0UAAAAAL48iOlThGAp9MUuzTiEZVqk8dKu', {action: 'homepage'}).then(function(token) {
         ...
      });
  });
  </script>
{% endblock %}